model_name_or_path: facebook/mbart-large-50-many-to-many-mmt
src_lang_token: en_XX
tgt_lang_token: nl_XX
forced_bos_token: nl_XX
per_device_eval_batch_size: 32
include_inputs_for_metrics: true

dataset_name: Helsinki-NLP/tatoeba_mt
dataset_config_name: eng-nld
dataset_split_name: test
src_column: sourceString
tgt_column: targetString

output_dir: results/en-nl/tatoeba_mt/facebook--mbart-large-50-many-to-many-mmt
