model_name_or_path: Helsinki-NLP/opus-mt-en-nl
data_trust_remote_code: true
src_lang_token: en
tgt_lang_token: nl
per_device_eval_batch_size: 64
include_inputs_for_metrics: true

dataset_name: Helsinki-NLP/tatoeba_mt
dataset_config_name: eng-nld
dataset_split_name: test
src_column: sourceString
tgt_column: targetString

output_dir: results/en-nl/tatoeba_mt/Helsinki-NLP--opus-mt-en-nl
