model_name_or_path: yhavinga/ul2-large-en-nl-v3
src_lang_token: English
tgt_lang_token: Dutch
per_device_eval_batch_size: 16
include_inputs_for_metrics: true

dataset_name: Helsinki-NLP/tatoeba_mt
dataset_config_name: eng-nld
dataset_split_name: test
src_column: sourceString
tgt_column: targetString

output_dir: results/en-nl/tatoeba_mt/yhavinga--ul2-large-en-nl-v3
