model_name_or_path: yhavinga/ul2-large-en-nl-v3
#src_lang_token: en_XX
#tgt_lang_token: nl_XX
#forced_bos_token: nl_XX
per_device_eval_batch_size: 4
include_inputs_for_metrics: true

dataset_name: Helsinki-NLP/tatoeba_mt
dataset_config_name: eng-nld
dataset_split_name: test
src_column: sourceString
tgt_column: targetString

output_dir: results/en-nl/tatoeba_mt/yhavinga--ul2-large-en-nl-v3
